import { AppBar, Box, Container, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";
import DirectionsBoatIcon from "@mui/icons-material/DirectionsBoat";
type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props): JSX.Element => {
  return (
    <Box>
      <Head>
        <title>Battleship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>{children}</Container>
    </Box>
  );
};

export default Layout;
